// WARNING: This file is automatically generated. Any changes will be lost the next time the generator is run.

export {default as rest_adapter} from './rest.adapter'
export {default as rest_service} from './rest.service'
