// WARNING: This file is automatically generated. Any changes will be lost the next time the generator is run.

export {default as RestAdapter} from './rest.adapter'
export {default as RestService} from './rest.service'
