// WARNING: This file is automatically generated. Any changes will be lost the next time the generator is run.

export {default as PouchAdapter} from './PouchAdapter'
export {default as PouchService} from './PouchService'
