name: CI

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  check:
    name: Build Checks
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Print environment variables
        run: printenv

      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and lint
        run: pnpm turbo run build //#lint

      - name: Reset git state
        run: git reset --hard

      - name: Build docs
        run: pnpm turbo run docs

      - name: Check working tree
        run: git diff --quiet || { echo 'Working tree is dirty. Did you forget to update the docs?'; exit 1; }
