name: CI

on:
  pull_request:
    types: [ opened, synchronize ]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  check:
    name: Build Checks
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Build, Test, and Lint
        uses: remedyred/check-action@v1.2.10
        with:
          SCRIPTS: prerelease

      - name: Check npm whoami
        run: npm whoami
