name: Release

on:
  push:
    branches:
      - main
      - next
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    steps:
      - name: Build, Test, and Lint
        uses: remedyred/check-action@v1.2.10
        with:
          SCRIPTS: prerelease
          NO_BAIL: true
          AUTO_COMMIT: true

      - name: Release
        run: npm whoami && pnpm run release:ci
