name: Release

on:
  push:
    branches:
      - main
      - next
  workflow_dispatch:

jobs:
  release:
    name: Release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and lint
        run: pnpm turbo run build docs //#fix

      - name: Release
        run: pnpm run release:ci
